Some steps needed to support ubuntu

diff --git a/dot_config/zsh/dot_zshrc.tmpl b/dot_config/zsh/dot_zshrc.tmpl
--- a/dot_config/zsh/dot_zshrc.tmpl
+++ b/dot_config/zsh/dot_zshrc.tmpl
@@ -15,12 +15,25 @@ export PATH="$HOME/bin:$HOME/.local/bin:$HOME/src/portbase-bin:$PULSAR_HOME/bin:
 autoload bashcompinit
 bashcompinit
 
-if [ -f "/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme" ]; then
+
+
+if [ -f "$HOME/.config/oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" ]; then
+  source $HOME/.config/oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
+elif [ -f "/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme" ]; then
   source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
+else
+  echo "WARNING: powerlevel10k not found!"
 fi
 
 # Path to your oh-my-zsh installation.
-ZSH=/usr/share/oh-my-zsh/
+if [ -d "$HOME/.config/oh-my-zsh" ]; then
+  ZSH=$HOME/.config/oh-my-zsh/
+elif [ -d "/usr/share/oh-my-zsh" ]; then
+  ZSH=/usr/share/oh-my-zsh/
+else
+  echo "ERROR: Oh-My-Zsh not found!"
+  exit 1
+fi
 
 # To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
 [[ -f ~/.config/zsh/.p10k.zsh ]] && source ~/.config/zsh/.p10k.zsh
@@ -44,7 +57,14 @@ COMPLETION_WAITING_DOTS="true"
 HIST_STAMPS="yyyy-mm-dd"
 
 # Would you like to use another custom folder than $ZSH/custom?
-ZSH_CUSTOM=/usr/share/zsh
+if [ -d "$HOME/.config/oh-my-zsh/custom" ]; then
+  ZSH_CUSTOM=$HOME/.config/oh-my-zsh/custom
+elif [ -d "/usr/share/zsh" ]; then
+  ZSH_CUSTOM=/usr/share/zsh/
+else
+  echo "ERROR: ZSH_CUSTOM not found!"
+  exit 1
+fi
 
 # Change foreground color of the autosuggest plugin
 ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'
@@ -95,7 +115,12 @@ alias ds='docker system'
 alias dv='docker volume'
 
 # Set tool replacement aliases
-alias cat='bat'
+if [ -f "/usr/bin/batcat" ]; then
+  alias cat='batcat'
+elif [ -f "/usr/bin/bat" ]; then
+  alias cat='bat'
+fi
+
 alias hex='hexyl'
 
 # Set MISC aliases
